### ISSUE TITLE
Swagger - Base address is wrong

### ISSUE THREAD

**Issue by carlosrgj** [bacen/pix-dict-quickstart#4]
Hello,
There is an inconsistency between reamed and spec.yaml https://github.com/bacen/pix-dict-api. The base address that is in the reamed is https://dict-h.pi.rsfn.net.br/dict/api/v1 and in the swagger it is https://dict-h.pi.rsfn.net.br/api/v1.
When doing a connectivity test on the dict, I came across this inconsistency.

I hope I've helped a bit.

**Comment by Guillerbr** [comment]
Esses links que citou estão offline?
É uma API?
Está conseguindo acessar ai?

**Comment by alcircesar** [comment]
Boa tarde.
Poderia confirmar se a url base é:  https://dict-h.pi.rsfn.net.br/dict/api/v1 ou https://dict-h.pi.rsfn.net.br/api/v1 ?

Obrigado.

**Comment by luizlaydner** [comment]
Corrigido. Não tem '/dict'.

https://github.com/bacen/pix-dict-quickstart/commit/efc08209352749913030fc7c5b17e9077c7add9f#diff-0730bb7c2e8f9ea2438b52e419dd86c9R72
